version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: bdM3S02
    ports:
      - 5430:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=bdM3S02